// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BilibiliLogo: typeof import('./src/components/icons/BilibiliLogo.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    Hero_buttons: typeof import('./src/components/Hero_buttons.vue')['default']
    HeroButtons: typeof import('./src/components/HeroButtons.vue')['default']
    ListProject: typeof import('./src/components/ListProject.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Project: typeof import('./src/components/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
